### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by mahansky** [CupOfTea696/TwoStream#10]
Hello,

I am using Laravel 5.2 and I would really like to use this package. Is there any chance of getting a support for it? Are you planning to release another version?
Btw I didn't know this package is for 5.1 - I installed it anyway (first time) and IT WORKED. Today, I was trying to continue coding but it didn't work anymore.. I made 0 changes (VCS confirmed)
This error shows up when I try to connect to the server from client:

```
Routing\WsRouter.php on line 1018

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method CupOfTea\TwoStream\Routing\Route::beforeFilters()
```

I heard L5.2 doesn't support Route filters anymore. Is there any quick fix around this? 

Thanks for info

**Comment by CupOfTea696** [comment]
Dropped filter support entirely, let me know if it runs fine now.

**Comment by mahansky** [comment]
I removed everything from the code, executed composer update and received this:

``` php
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class CupOfTea\TwoStream\Routing\WsRouter contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (CupOfTea\TwoStream\Contracts\Rou
  ting\Registrar::before, CupOfTea\TwoStream\Contracts\Routing\Registrar::after, CupOfTea\TwoStream\Contracts\Routing\Registrar::filter)

vendor\cupoftea\twostream\src\Routing\WsRouter.php on line 969
```

**Comment by CupOfTea696** [comment]
Forgot the Contracts, whoops
