### ISSUE TITLE
Error installing twoStream

### ISSUE THREAD

**Issue by YnievesDotNet** [CupOfTea696/TwoStream#3]
i try install twostream in Laravel 5.1, and I get this.

 [Symfony\Component\Debug\Exception\FatalErrorException]
  CupOfTea\TwoStream\TwoStreamServiceProvider::CupOfTea\TwoStream{closure}(): Failed opening required 'D:\xampp\htdo
  cs\plantel.ynieves.local\app\Ws/routes.php' (include_path='D:\xampp\htdocs\plantel.ynieves.local\vendor/phpseclib/p
  hpseclib/phpseclib;.;D:\xampp\php\PEAR')

Thanks

I use PHP 5.6.4,

**Comment by YnievesDotNet** [comment]
I solve creating app/Ws/routes.php, in the install process the system can't check this parameter, or create during this process,

Thanks.

YnievesDotNet

**Comment by YnievesDotNet** [comment]
And now have problem, I have that error

InvalidArgumentException in UrlGenerator.php line 558:
Action App\Ws\Controllers\BackendController@index not defined.

This route is not for WebSocket, why this package try get all my routes of system??

Thanks

**Comment by CupOfTea696** [comment]
Could I maybe see some of your code and some more info on the error you're getting?

**Comment by YnievesDotNet** [comment]
this error is only activating wsRoute alias.

the site work ok, but, when I try activate the 4 lines en config/app, the error has return.

```
CupOfTea\TwoStream\TwoStreamServiceProvider::class,
.....
        'TwoStream' => CupOfTea\TwoStream\Facades\TwoStream::class,
        'WsRoute'   => CupOfTea\TwoStream\Facades\WsRoute::class,
        'WsSession' => CupOfTea\TwoStream\Facades\WsSession::class,
```

The problem is with the route, he capture all my controller and search the controllers inside app/Ws/Controller, and not in app/Http/Controllers.

Thanks.

**Comment by YnievesDotNet** [comment]
Do you have IMO, Facebook, any IM account, thanks.

Yoinier,

**Comment by YnievesDotNet** [comment]
This code return error.

```
$menu->add('Panel', array('action' => 'BackendController@index'))->data('role', 'user');
```

Yoinier.

every function action, url, route, etc, return error, controller not found in app/Ws/....

Thanks.

**Comment by CupOfTea696** [comment]
Are you still using the routes.php file in the http folder? Normal routes should still go in there, using the Laravel Route facade. Only the routes for WebSockets need to go in the ws routes.php, using the WsRoute facade.

**Comment by YnievesDotNet** [comment]
but something has wront them. I suposed that your exposed, but dont work do.

my routes are declarated in app/Http/routes.php, and work fine.

now, when I added the 4 line for config/app.php the system search the controlles el Ws instead Http, I thinks the problems is in /vendor/cupoftea/TwoStream/src/Routing...

Thanks.

**Comment by CupOfTea696** [comment]
Could you show me your full route.php files (both http and ws) and the controller TwoStream can't find?

**Comment by YnievesDotNet** [comment]
## app/Ws/routes.php

```
WsRoute::unsubscribe('chat/room/{id}', function($id)
{
    return 'You disconnected to chat room ' . $id;
});

WsRoute::subscribe('chat/room/{id}', function($id)
{
    return 'You connected to chat room ' . $id;
});

WsRoute::publish('blog/create', function()
{
    $data = Request::input('data');
});

WsRoute::call('math/mult/{a}/{b}', function($a, $b)
{
    return $a * $b;
});
```

---

## app/Http/routes.php

```
Route::get('/', function () {
    return view('welcome');
});
/*
 * Message Controller
 */
Route::get('messages/', 'Backend\MessagesController@index');
Route::get('messages/create', 'Backend\MessagesController@create');
```

---

Thanks.

**Comment by CupOfTea696** [comment]
Where exactly are you calling the menu->add?

```
$menu->add('Panel', array('action' => 'BackendController@index'))->data('role', 'user');
```

**Comment by YnievesDotNet** [comment]
this is an example, any call a action(), url(), route(), return error.
app/Http/routes.php

``` php
Route::get('backend','BackendController@index');
```

and my menu middleware

``` php
    public function handle($request, Closure $next)
    {
        Menu::make('sidebar', function($menu) {
            $menu->add('Panel', array('action' => 'BackendController@index'))->data('role', 'user');
            ...
        return $next($request);
    }
```

this return error.

**Comment by CupOfTea696** [comment]
Found the problem. It's getting late so I'll probably look for a fix tomorrow.

**Comment by YnievesDotNet** [comment]
thanks, waiting for you.

**Comment by CupOfTea696** [comment]
Actually, it turned out to be something really simple so I just did it now. Let me know if everything works fine now.

**Comment by YnievesDotNet** [comment]
Ready, the problem is out now. I'm now write the websocket logic, any new thing post a new issue, thanks.

Good project. Thanks.

You have any example of this package?

Thanks.

**Comment by CupOfTea696** [comment]
No problem :)

And no, I don't have any examples. But there is a Documentation and a full API browser that should get you on the right track.
