### ISSUE TITLE
Error starting the server...

### ISSUE THREAD

**Issue by YnievesDotNet** [CupOfTea696/TwoStream#4]
I catch this

   TwoStream Server listening on IP [0.0.0.0] with port [1111]

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Ratchet\Wamp\TopicAccessTrait' not found

Thanks.

**Comment by YnievesDotNet** [comment]
I find the file in your fork of reactphp/Ratchen, but in the original this file has been removed.

Thanks

**Comment by CupOfTea696** [comment]
http://twostream.cupoftea.io/docs/installation/#install-via-composer

**Comment by CupOfTea696** [comment]
You need to add the VCS repository to your composer.json

**Comment by YnievesDotNet** [comment]
this is do.

But load other version.

**Comment by YnievesDotNet** [comment]
I download manually your version. but when I ejecute composer update download the last version, losting these file.

**Comment by CupOfTea696** [comment]
If you did everything correctly, it should download the right version of Ratchet.
