### ISSUE TITLE
Getting an error when running the php artisan twostream:install

### ISSUE THREAD

**Issue by Nisthar** [CupOfTea696/TwoStream#8]
TwoStream Server listening on IP [0.0.0.0] with port [1111]

  [ErrorException]
  Argument 1 passed to CupOfTea\TwoStream\Wamp\WampServer::__construct() must
   be an instance of CupOfTea\TwoStream\Wamp\WampServerInterface, instance of
   CupOfTea\TwoStream\Server\Dispatcher given, called in E:\wamp\www\reviewil
  l\reviewillcore\vendor\cupoftea\twostream\src\Server.php on line 252 and de
  fined
I am getting this error when running php artisan twostream:install. Before this error, i was getting TopicAccessTrait not found in Ratchet\Wamp. I had to manually download your ratchet fork and replace my downloaded ratchet files. I installed the package using composer and don't know why the files were missing or why the above mentioned error occurs?

**Comment by Nisthar** [comment]
Is this an error with my setup or the library?

**Comment by CupOfTea696** [comment]
No it's very likely a bug within TwoStream, I've done some refactoring and it probably broke some stuff.

**Comment by CupOfTea696** [comment]
Alright, so what happened is that I moved the TopicAccessTrait to TwoStream itself so it wouldn't depend on my own branch of Ratchet anymore (that was just a bad decision) but I missed quite a few `use` statements in doing so. Let me know if your problem is now resolved.

**Comment by Nisthar** [comment]
Ok. Let me try install it again.
