### ISSUE TITLE
Call to a member function getIterator() on a non-object

### ISSUE THREAD

**Issue by Nisthar** [CupOfTea696/TwoStream#9]
TwoStream Server listening on IP [0.0.0.0] with port [5555]
      Error: The payload is invalid.

 [Symfony\Component\Debug\Exception\FatalErrorException]
 Call to a member function getIterator() on a non-object

My server-side:

```
     <?php

          WsRoute::subscribe('/test', function()
        {
        return 'You connected to chat room ';
       });
```

My client side:

```
            if ("WebSocket" in window)
            {
               alert("WebSocket is supported by your Browser!");

               // Let us open a web socket
               var ws = new WebSocket("ws://localhost:5555/test");

               ws.onopen = function()
               {
                  // Web Socket is connected, send data using send()
                  ws.send("Message to send");
                  alert("Message is sent...");
               };

               ws.onmessage = function (evt) 
               { 
                  var received_msg = evt.data;
                  alert("Message is received...");
               };

               ws.onclose = function()
               { 
                  // websocket is closed.
                  alert("Connection is closed..."); 
               };
            }

            else
            {
               // The browser doesn't support WebSocket
               alert("WebSocket NOT supported by your Browser!");
            }
```

**Comment by Nisthar** [comment]
@CupOfTea696 Is this an error with library or my setup? 
because i think i already have another version Ratchet installed in my workspace.

**Comment by CupOfTea696** [comment]
Sorry, I've been busy. Let me check it and I'll get back to you asap!

**Comment by CupOfTea696** [comment]
I think it might be an issues with your front-end. TwoStream uses the WAMP v1 protocol to communicate over the WebSocket connection. Try using a front-end library like [Autobahn.js legacy](http://autobahn.ws/js/reference_wampv1.html) to send messages.

**Comment by Nisthar** [comment]
@CupOfTea696 Still getting the same error using autobahn.js. Did you tested it on your pc?

**Comment by CupOfTea696** [comment]
That's a bummer. Could you show me your autobahn code?

**Comment by Nisthar** [comment]
```
 ab.connect(
      // The WebSocket URI of the WAMP server
         "ws://localhost:1111",

         // The onconnect handler
          function (session) {
       // WAMP session established here ..
        console.log(session);
      },

        // The onhangup handler
          function (code, reason, detail) {
          // WAMP session closed here ..
           },

     // The session options
   {
       'maxRetries': 60,
       'retryDelay': 2000
    }
   );
```

**Comment by CupOfTea696** [comment]
I'll look into it when I have some time! Sorry this is taking so long, things are quite busy atm.

**Comment by Nisthar** [comment]
@CupOfTea696 ok np. just need to confirm if the error is in lib or the setup.

**Comment by CupOfTea696** [comment]
Probably in the lib tbh. I'll have a look at it tomorrow.

**Comment by CupOfTea696** [comment]
Alright, so there were some 5.2 compatibility issues, they should be sorted now.

Please note that you'll also configure your nginx/Apache to proxy your websocket calls. If you connect through localhost it won't send the cookies along with your http upgrade request to open the WS connection, and this will make it impossible for TwoStream to identify the laravel session ID, and authenticated user etc.

for nginx it'd be something like this (where 1111 is the port TwoStream is listening on and 2222 the port you'll send your front-end request to):

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream websocket {
        server localhost:1111;
}

server {
    listen 2222;
    location / {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_redirect off;
    }
}
```

Alternatively, you could also set the server part up to be a subdomain (e.g. ws.site.local) or a specific location in your existing server section generated by homestead (just copy the location section and change `location /` to something like `location /websocket/`), that way you could connect with the front end to `ws.site.local` or `site.local/websocket` without needing to specify a port.

The nginx config file you'll need to edit should be located at `/etc/nginx/sites-available/site.local` in homestead.

More details about the nginx configuration [here](https://www.nginx.com/blog/websocket-nginx/) and [here](https://gist.github.com/octaflop/4991052).

**Comment by Nisthar** [comment]
@CupOfTea696 Btw my server is apache. So i assume there is no easy way to use websockets in php.

**Comment by CupOfTea696** [comment]
It should be possible with Apache as well, but you'd have to google it.

**Comment by Nisthar** [comment]
Thanks. I'll try it.
